### ISSUE TITLE
Crashlytics error

### ISSUE THREAD

**Issue by yarik1988** [pollfish/android-sdk-pollfish#12]
I recently incorporated pollfish into my app, and had couple of errors 
```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@e370b56 rejected from java.util.concurrent.ThreadPoolExecutor@d6837d7[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
       at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:242)
       at com.pollfish.internal.z1.a(z1.java:13)
       at com.pollfish.internal.a1.a(a1.java:1)
       at com.pollfish.internal.x1.run(x1.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```
What may be the reason of it?

**Comment by fotism23** [comment]
Hello, @yarik1988 

Thank you for the report.

We have released version v6.0.4 which fixed the reported issue.
