### ISSUE TITLE
kotlin version of sample app when launch and after few seconds app get crashed

### ISSUE THREAD

**Issue by mir8bloxx** [pollfish/android-sdk-pollfish#19]
**Device Info : Huawei 8x, android 10**
Logs along with crash message at the end :

`FATAL EXCEPTION: main
Process: com.prodege.sample, PID: 8240
java.lang.NullPointerException: throw with null exception
	at com.prodege.internal.j4.a(SourceFile:6)
	at com.prodege.internal.e3.a(SourceFile:2)
	at com.prodege.internal.e3$b.invoke(SourceFile:15)
	at com.prodege.internal.d1.a(SourceFile:32)
	at com.prodege.internal.d1$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
`

`channel '161b7e9 com.prodege.sample/com.prodege.sample.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
notifyActivityState pkg:com.prodege.sample/com.prodege.sample.MainActivity state:20 fg:false mUid:11110`

**Comment by fotism23** [comment]
Hello @mir8bloxx 

Thanks for the report. We have released 7.0.0-beta07 fixing this issue.

Closing this for now, please give that a try and feel free to reopen if the issue persists.
